#!/usr/bin/env ruby
# frozen_string_literal: true

if ENV['THREDDED_CREATE_APP_BIN_SIMPLECOV_COVERAGE']
  require_relative '../spec/simplecov_bin_helper'
end

require 'thredded_create_app/cli'
ThreddedCreateApp::CLI.start(ARGV)
