# A Dockerfile for development.

FROM ruby:2.6.3-alpine

RUN apk update && \
    apk add --no-cache \
    # Runtime deps
    ruby-bigdecimal ruby-io-console ruby-json tzdata nodejs yarn bash \
    # Bundle install deps
    build-base ruby-dev libc-dev libffi-dev linux-headers gmp-dev libressl-dev libxml2-dev libxslt-dev \
    mariadb-connector-c-dev postgresql-dev sqlite-dev git && \
    gem install bundler:2.1.4

ENV APP_HOME /<%= app_name %>
WORKDIR $APP_HOME
RUN mkdir -p $APP_HOME

# Copy Gemfile and run bundle install first to allow for caching
COPY Gemfile Gemfile.lock $APP_HOME/
RUN bundle install

COPY Rakefile config.ru app/ bin/ config/ db/ lib/ script/ spec/ $APP_HOME/
